SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS  D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;

SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS  D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
WHERE DEPARTMENT_NAME='IT';

SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS  D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;

SELECT E.FIRST_NAME,E.LAST_NAME,D.LOCATION_ID
FROM EMPLOYEES E
JOIN DEPARTMENTS  D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;

SELECT E.FIRST_NAME,E.LAST_NAME,D.MANAGER_ID
FROM EMPLOYEES E
JOIN DEPARTMENTS  D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;

SELECT E.FIRST_NAME,E.LAST_NAME,J.JOB_TITLE
FROM EMPLOYEES E 
JOIN JOBS J 
ON E.JOB_ID=J.JOB_ID;

SELECT E.FIRST_NAME,E.LAST_NAME,J.JOB_TITLE,J.MAX_SALARY
FROM EMPLOYEES E 
JOIN JOBS J 
ON E.JOB_ID=J.JOB_ID;

SELECT E.FIRST_NAME,E.LAST_NAME,J.JOB_TITLE,J.MIN_SALARY
FROM EMPLOYEES E 
JOIN JOBS J 
ON E.JOB_ID=J.JOB_ID;

SELECT E.FIRST_NAME,E.LAST_NAME,J.JOB_TITLE,J.MAX_SALARY,J.MIN_SALARY
FROM EMPLOYEES E 
JOIN JOBS J 
ON E.JOB_ID=J.JOB_ID;


SELECT E.FIRST_NAME,E.LAST_NAME,E.SALARY,PHONE_NUMBER,HIRE_DATE,MANAGER_ID,COMMISSION_PCT,
J.JOB_TITLE,J.MAX_SALARY-J.MIN_SALARY AS DIFF
FROM EMPLOYEES E 
JOIN JOBS J 
ON E.JOB_ID=J.JOB_ID;
